### ISSUE TITLE
Is this work still active?

### ISSUE THREAD

**Issue by gatemezing** [BuildingSMART/ifcOWL#6]
DEar all,
I wanted to know if this repository is still active? TIA

**Comment by pipauwel** [comment]
Hi gatemezing, 
No, this is not active any more. There is no real plan for OWL or RDF in buildingSMART as far as I know.

**Comment by gatemezing** [comment]
Oh sad! I see growing interest in using semantics to combine assets with IFC standards - like in railways

**Comment by pipauwel** [comment]
I agree entirely. I believe that most of the graph-oriented and semantics-oriented communities are working on this elsewhere. Within buildingSMART, these things get subsumed by bSDD, as far as I understand.
